name: CI Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-master
      
      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev

      - name: Build
        run: |
            zig build debugtext_print -DZigCC --summary all
            zig build clear -DZigCC --summary all
            zig build sgl_context -DZigCC --summary all
            zig build cube -DZigCC --summary all
            zig build blend -DZigCC --summary all
